  - name: configure firewall for http and https
    ufw:
      rule: allow
      to_port: "{{ item }}"
    with_items:
       - 80
       - 443
    when: inventory_hostname.find("lin") != -1

  - name: configure firewall for ssh port 22
    ufw:
      rule: allow
      src: "{{ item }}"
      to_port: 22
    with_items:
       - 24.216.224.114
       - 173.163.31.177
       - 207.244.76.238
       - 24.216.224.112
       - 54.235.155.255
       - 69.197.156.2
       - 104.243.47.251
       - 23.227.198.88
       - 23.227.206.33
       - 104.243.47.226
       - 23.227.197.225
       - 108.61.128.241
       - 37.72.169.1
       - 157.245.93.41
       - 45.63.74.241
       - 149.28.52.17
       - 104.236.197.91
       - 45.63.93.97
       - 67.207.83.182
    when: inventory_hostname.find("lin") != -1

  - name: configure firewall for ssh port 9001
    ufw:
      rule: allow
      src: "{{ item }}"
      to_port: 9001
    with_items:
       - 24.216.224.114
       - 173.163.31.177
       - 207.244.76.238
       - 24.216.224.112
       - 54.235.155.255
       - 69.197.156.2
       - 104.243.47.251
       - 23.227.198.88
       - 23.227.206.33
       - 104.243.47.226
       - 23.227.197.225
       - 108.61.128.241
       - 37.72.169.1
       - 157.245.93.41
       - 45.63.74.241
       - 149.28.52.17
       - 104.236.197.91
       - 45.63.93.97
       - 67.207.83.182
    when: inventory_hostname.find("lin") != -1

  - name: ufw enable
    ufw:
      state: enabled
      policy: deny
      direction: incoming
    when: inventory_hostname.find("lin") != -1
