---
- name: Advanced EC2 Instance Provisioning
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: us-west-1
    vpc_id: vpc-12345678
    ec2_key_name: my-key
    ec2_instance_type: t2.micro
    ec2_image_id: ami-0c55b159cbfafe1f0
    ec2_security_group_name: my-ec2-security-group
    ec2_tag_Name: MyEC2Instance

  tasks:
    - name: Create EC2 Security Group
      ec2_group:
        name: "{{ ec2_security_group_name }}"
        description: EC2 Security Group for MyApp
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
      register: ec2_security_group

    - name: Launch an EC2 instance
      ec2:
        region: "{{ aws_region }}"
        key_name: "{{ ec2_key_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image_id }}"
        group: "{{ ec2_security_group_name }}"
        wait: yes
        instance_tags:
          Name: "{{ ec2_tag_Name }}"
      register: ec2

    - name: Display EC2 instance information
      debug:
        var: ec2

    - name: Add new EC2 instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_instances
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 10
        timeout: 300
      loop: "{{ ec2.instances }}"

